{{- if .Values.service.metallbEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-lb
  annotations:
    metallb.universe.tf/address-pool: lb-ip-pool
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  type: LoadBalancer
{{- end }}
