
ingress-nginx:
  controller:
    service:
      enabled: true
      type: "LoadBalancer"
      # externalTrafficPolicy: "Local"
      annotations:
        metallb.universe.tf/address-pool: lb-ip-pool # Get IP from metallb