## Override subchart config
vaultwarden:
  data:
    name: "vaultwarden-data"
    size: "8Gi"
    class: smb


  ingress:
    enabled: true
    class: nginx
    hostname: vault.fallow.app
    tlsSecret: vaultwarden-tls-secret
    additionalAnnotations:
      cert-manager.io/cluster-issuer: letsencrypt
      cert-manager.io/revision-history-limit: "2"

  domain: https://vault.fallow.app