
jellyfin:
  #  Can try changing controller
  # controller:
  #   type: "statefulset"

  env:
    TZ: "America/Toronto" 

  persistence:
    config:
      enabled: true
      storageClass: local-path # the sqlite db locks if using smb
      accessMode: ReadWriteOnce # local-path ReadWriteOnce and ReadWriteOncePod

    # Cache does NOT contain temporary transcoding data.
    cache:
      enabled: true
      mountPath: /cache
      accessMode: ReadWriteMany
      size: 5Gi
      storageClass: smb

    media:
      enabled: true
      mountPath: /media
      accessMode: ReadWriteMany
      size: 300Gi
      storageClass: smb