uptime-kuma:

  ## Persistence
  useDeploy: false
  volume:
    accesMode: ReadWriteMany ## Using smb
    size: 3Gi
    storageClassName: smb

  
  ## Ingress
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: kuma.fallow.app
        paths:
          - path: /
            pathType: ImplementationSpecific
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      cert-manager.io/revision-history-limit: "2"
      ## Default chart annotations
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/server-snippets: |
        location / {
          proxy_set_header Upgrade $http_upgrade;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   Upgrade $http_upgrade;
          proxy_cache_bypass $http_upgrade;
        }
    tls:
    - hosts: 
      - kuma.fallow.app
      secretName: kuma-tls-secret
      